### ISSUE TITLE
Signal Command Map injector not passing in application domain to child

### ISSUE THREAD

**Issue by chrisnojima** [joelhooks/signals-extensions-CommandSignal#12]
Hi,
I'm using signal commands + your modular extensions to robolegs. I have some submodules loading up and noticed a bug where if i make a command inject some classes that exist in my submodule, even if the command is in a submodule it'll complain that it can't get the descritpion from the application domain and the injection will fail. This is fixed by changing this line of code in  SignalContext.

public function get signalCommandMap():ISignalCommandMap
{
    return _signalCommandMap || (_signalCommandMap = new SignalCommandMap(injector.createChild(injector.
                    applicationDomain)));
}

**Comment by joelhooks** [comment]
This has been fixed (by you!)
