### ISSUE TITLE
Build failure when missing report folder

### ISSUE THREAD

**Issue by texastoland** [joelhooks/signals-extensions-CommandSignal#19]
My build failed until I manually created my report (report.loc) folder.

**Comment by joelhooks** [comment]
No patch?

On Jul 10, 2011, at 16:21, dnalot
reply@reply.github.com
wrote:

**Comment by texastoland** [comment]
I'd have to figure out Ant ;) I will later this week if you don't know the fix off the top of your head.

**Comment by robertpenner** [comment]
I fixed the JUnit report issue in my fork.

**Comment by texastoland** [comment]
I more gracefully fixed the other issue too. I need to commit it to mine.
