### ISSUE TITLE
Build FLEX_HOME not configurable in properties file

### ISSUE THREAD

**Issue by texastoland** [joelhooks/signals-extensions-CommandSignal#20]
…because Fail task before Property file defined and exclusive to environment.

**Comment by joelhooks** [comment]
I'm pretty sure your errors are user related. ;)

On Jul 10, 2011, at 16:25, dnalot
reply@reply.github.com
wrote:

**Comment by texastoland** [comment]
I'm pretty sure you just goaded me into a patch because there's a comment that purports I can set FLEX_HOME in my properties ;)

**Comment by joelhooks** [comment]
FLEX_HOME is a system envar and not set in the ant at all

**Comment by texastoland** [comment]
Well the comment needs patched then :P Regardless my patch let's you set it in build.properties for those who prefer not to muck up their path. Especially on Mac where you can set environment variables in literally a dozen distinct places depending EG you need application access to them.

**Comment by fljot** [comment]
Joel, I'm sure you know, just reminding — best way is to have a build.properties.template(under git) and build.properties(user-made out of template), where user could enter proper path to desired Flex SDK. These will make build process easier.

**Comment by joelhooks** [comment]
I don't think it is particularly challenging as is ;)

On Sat, Jul 30, 2011 at 5:55 PM, fljot
reply@reply.github.com
wrote:

**Comment by fljot** [comment]
Well the shortest workaround is running build via "ant -Denv.FLEX_HOME=/path/to/flex/sdk"
