### ISSUE TITLE
SignalContext no workee with RL 1.1.0

### ISSUE THREAD

**Issue by msakrejda** [joelhooks/signals-extensions-CommandSignal#3]
I tried building my project with RL 1.1.0b7 (which I believe I need for the Modular RL extension--in any case, 1.0.3 was missing some property or other), and while it builds fine, at runtime, I get the error:

Variable org.robotlegs.base:ContextBase::Injector is not defined

in SignalContext.as, line 24. Any ideas?

**Comment by joelhooks** [comment]
I haven't updated it for 1.1 yet. I will make a branch and get it rolling.

**Comment by msakrejda** [comment]
Ok, thanks. But my assessment is correct, right? I need 1.1 for Modular RL (to set the injector, I believe)?

**Comment by joelhooks** [comment]
Can you isolate with a code example for me? My cafe example works with my current version. Let me push my development branch that makes use of RL 1.1

**Comment by msakrejda** [comment]
Actualy, looking at the source, I should just be able to rebuild it against 1.1 (since the injector simply moved down from the ContextBase to the Context). Let me try that and I'll report back.

**Comment by joelhooks** [comment]
I pushed my development branch that uses RL 1.1

**Comment by joelhooks** [comment]
did you get it to work?

**Comment by msakrejda** [comment]
Yep, looks like (I found out I had to upgrade the extension while in the middle of some development, so all _my_ pieces aren't working yet, but I'm not getting any errors from the extension). All it took was a rebuild against RL 1.1. Thanks.
