### ISSUE TITLE
Can't map signal to command in SignalCommand::execute()

### ISSUE THREAD

**Issue by Nek** [joelhooks/signals-extensions-CommandSignal#4]
If I move this line
signalCommandMap.mapSignalClass(OrderReceived, FindOrderDetails);
from context startup into StartListenToOrders command the mapping breaks.

**Comment by joelhooks** [comment]
It is impossible to say what the issue is out of context like this. Need more details, sample code, etc.

**Comment by Nek** [comment]
Yep. Have added this one in haste. I'll provide details later on.

**Comment by joelhooks** [comment]
I am closing this lacking more details

**Comment by Nek** [comment]
I agree. As far as I remember the issue was fixed with the update of robotlegs/as3signals. Sorry for not writing it here in a comment earlier.

**Comment by joelhooks** [comment]
It is more my neglect as a project parent. No worries :>

**Comment by Nek** [comment]
ok )
