### ISSUE TITLE
SignalCommandMap doesn't work with ArrayCollection payload.

### ISSUE THREAD

**Issue by Nek** [joelhooks/signals-extensions-CommandSignal#5]
If I try to dispatch a mapped signal with this type of payload I get:
Error: Unknown Property: 'constructor'
at mx.collections::ListCollectionView/http://www.adobe.com/2006/actionscript/flash/proxy::getProperty()

The signals works well with this payload type if I don't map 'em. The problem only happens with signalCommandMap.
For a quick workaround I have changed my payload type to Array and it did the trick.

**Comment by joelhooks** [comment]
I pushed revision to master. It requires RL 1.1b and SwiftSuspenders 1.5. I added a unit test to make sure AC injection works. It does. This is a SwiftSuspenders thing. I don't know which version you are using, but you should go ahead and update that as well. RL 1.1 is stable, and SS1.5 is released, so use the latest and you'll be set :>

**Comment by Nek** [comment]
Thanks, Joel. I use Robotlegs 1.0.3 so it's definitely time for update :)
